trigger: none

resources:
  repositories:
  - repository: Pipelines 
    type: git
    name: ReleasePlatformAutomation/Pipelines
    ref: master
  - repo: self
stages:
- stage: Build
  jobs:  
  - job: Build
    timeoutInMinutes: 360
    displayName: Build
    pool:
      name: FA-ContainersPool-Prod
      demands:
        - AWS -equals True

    container:
        image: ssppaps1arpscr1.azurecr.io/wincore19-vs17ent-arps-buildimage1:latest
        endpoint: DevOps-ACR-PROD

    steps:
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'Source/TEN.sln'
        feedsToUse: 'select'

    - task: VSBuild@1
      inputs:
        solution: 'Source/TEN.sln'
        msbuildArgs: '/p:OutDir=$(Build.ArtifactStagingDirectory)\ /p:DBScriptsSource=$(Build.SourcesDirectory)\DBAutomation\RollScripts\*.*'
        platform: '$(BuildConfiguration)'
        configuration: '$(BuildPlatform)'

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'TenMVC/TenMVC.sln'
        feedsToUse: 'select'

    - task: VSBuild@1
      inputs:
        solution: 'TenMVC/TenMVC.sln'
        msbuildArgs: '/p:OutDir=$(Build.ArtifactStagingDirectory)'
        platform: '$(BuildConfiguration)'
        configuration: '$(BuildPlatform)'
    - template: TQA/TQA.yml@Pipelines
        parameters: 
            Run_Veracode_Upload: 'false'                                   # True or false
            Run_SonarQube_Analysis: 'false'                                # True or false
            Run_TQAProcess: 'false'                                        # True or false
            Folders_To_Zip: '_PublishedApplications|_PublishedWebsites'    # _PublishedApplications|_PublishedWebsites
            SourcePath_to_Zip: '$(build.artifactstagingdirectory)'         # $(build.artifactstagingdirectory)
            ScanOption: 'SB'                                               # SB - Sandbox scan, PScan - Policy scan
            VeracodeAppName: 'TEN'
            VeracodeAppID: '196338'
            VeracodeSandBoxID: '2627082'
            EmailRecipients: 'FAI-TEN@firstam.com'
            SQHostServer: 'snavnappsqub001.corp.firstam.com'
            SQKey: 'TEN'
            SQProject: 'TEN'
            SonarQubeURI: 'http://snavnappsqub001.corp.firstam.com:9000/api/resources?resource=TEN'
